"""
Django settings for sopds project.

Generated by 'django-admin startproject' using Django 1.9.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
from collections import OrderedDict
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / "...".
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() in ("1", "true", "yes", "on")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured("DJANGO_SECRET_KEY is required")

GRACEFUL_TIMEOUT = int(os.getenv("GRACEFUL_TIMEOUT", "25"))
GUNICORN_WORKERS = int(os.getenv("GUNICORN_WORKERS", "0")) or os.cpu_count()

# Console logging for Django, application code, scanner orchestration, and workers.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "below_error": {
            "()": "config.logging_filters.BelowErrorFilter",
        },
    },
    "formatters": {
        "verbose": {
            "format": "{asctime} [{levelname}] {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "stdout": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["below_error"],
            "stream": "ext://sys.stdout",
        },
        "stderr": {
            "level": "ERROR",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "stream": "ext://sys.stderr",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["stdout", "stderr"],
            "level": "INFO",
            "propagate": False,
        },
        "opds_catalog": {
            "handlers": ["stdout", "stderr"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "ops": {
            "handlers": ["stdout", "stderr"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "web_backend": {
            "handlers": ["stdout", "stderr"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "*").split(",")
    if h.strip()
]

CSRF_TRUSTED_ORIGINS = [
    h.strip()
    for h in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if h.strip()
]

# Application definition
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

INSTALLED_APPS = [
    "ops",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "opds_catalog",
    "web_backend",
    "django.contrib.admin",
    "django.contrib.staticfiles",
    "constance",
]

MIDDLEWARE = [
    "django.middleware.cache.UpdateCacheMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "web_backend.timezone.TimezoneMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "opds_catalog.middleware.BasicAuthMiddleware",
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    "opds_catalog.middleware.SOPDSLocaleMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 'django.middleware.cache.CacheMiddleware',
    # 'opds_catalog.middleware.FetchFromCacheMiddleware',
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "web_backend.timezone.timezone_context",
                "web_backend.views.sopds_processor",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Scanner-agnostic database connection tuning (affects both scanner and web).
SOPDS_DB_CONN_MAX_AGE = int(os.environ.get("SOPDS_DB_CONN_MAX_AGE", "600"))
SOPDS_DB_HEALTH_CHECKS = os.environ.get("SOPDS_DB_HEALTH_CHECKS", "True").lower() in (
    "1",
    "true",
    "yes",
    "on",
)

# SOPDS DATABASE SETTINGS START

import dj_database_url  # noqa: E402  — import after os

DATABASE_URL = os.environ.get("DATABASE_URL")
if not DATABASE_URL:
    raise ImproperlyConfigured("DATABASE_URL is required")

DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=SOPDS_DB_CONN_MAX_AGE,
        conn_health_checks=SOPDS_DB_HEALTH_CHECKS,
    )
}
if DATABASES["default"]["ENGINE"] not in {
    "django.db.backends.postgresql",
    "django.db.backends.mysql",
}:
    raise ImproperlyConfigured(
        "Unsupported database backend in DATABASE_URL; supported backends are "
        "PostgreSQL and MySQL/MariaDB"
    )

# Advisory locks are connection-scoped. Keep the scanner lock on a dedicated
# connection so retries may safely reset the default scanner connection.
DATABASES["scanner_lock"] = {
    **DATABASES["default"],
    "CONN_MAX_AGE": 0,
    "CONN_HEALTH_CHECKS": False,
    "TEST": {"MIRROR": "default"},
}

# SOPDS DATABASE SETTINGS FINISH

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation."
        "UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LOCALE_PATHS = (os.path.join(BASE_DIR, "config/locale"),)

TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

CACHE_BACKEND = "locmem://"
CACHE_MIDDLEWARE_KEY_PREFIX = "sopds"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"

CONSTANCE_ADDITIONAL_FIELDS = {
    "book_extensions": [
        "django.forms.MultipleChoiceField",
        {
            "widget": "django.forms.CheckboxSelectMultiple",
            "choices": ((".fb2", "FB2"), (".epub", "EPUB"), (".mobi", "MOBI")),
        },
    ],
    "language_select": [
        "django.forms.fields.ChoiceField",
        {
            "widget": "django.forms.Select",
            "choices": (("ru-RU", "Russian"), ("en-US", "English")),
        },
    ],
}

CONSTANCE_CONFIG = OrderedDict(
    [
        ("SOPDS_LANGUAGE", ("en-US", _("Select language"), "language_select")),
        (
            "SOPDS_BOOK_EXTENSIONS",
            (
                [".fb2", ".epub", ".mobi"],
                _("List of managed book files extensions"),
                "book_extensions",
            ),
        ),
        (
            "SOPDS_SCAN_START_DIRECTLY",
            (
                os.getenv("SOPDS_SCAN_START_DIRECTLY", "False").lower()
                in ("1", "true", "yes", "on"),
                _("Turn once scanning directly"),
            ),
        ),
        ("SOPDS_CACHE_TIME", (1200, _("Pages cache time"))),
        ("SOPDS_AUTH", (True, _("Enable authentication"))),
        ("SOPDS_ALPHABET_MENU", (True, _("Enable alphabet submenu"))),
        ("SOPDS_DOUBLES_HIDE", (True, _("This flag hides found doublicates"))),
        ("SOPDS_COVER_SHOW", (True, _("This flag activate showing cover of books"))),
        ("SOPDS_SPLITITEMS", (300, _("Max subitems count in alphabet menuitem"))),
        ("SOPDS_MAXITEMS", (60, _("Max items on page"))),
        (
            "SOPDS_TITLE_AS_FILENAME",
            (True, _("Create downloaded filename from book title")),
        ),
        (
            "SOPDS_ZIP_ENABLE",
            (
                os.getenv("SOPDS_ZIP_ENABLE", "True").lower()
                in ("1", "true", "yes", "on"),
                _("This flag activate zip files scanning"),
            ),
        ),
        (
            "SOPDS_ZIP_SKIP_UNCHANGED",
            (
                os.getenv("SOPDS_ZIP_SKIP_UNCHANGED", "True").lower()
                in ("1", "true", "yes", "on"),
                _("Skip unchanged ZIP archives on re-scan by comparing file size"),
            ),
        ),
        (
            "SOPDS_ZIP_CODEPAGE",
            (
                os.getenv("SOPDS_ZIP_CODEPAGE", "cp866"),
                _("Set codepage for filenames inside zipfile"),
            ),
        ),
        (
            "SOPDS_INPX_ENABLE",
            (
                os.getenv("SOPDS_INPX_ENABLE", "True").lower()
                in ("1", "true", "yes", "on"),
                _(
                    "Enables read metadata from inpx-file (and stop"
                    " scanning deeper from ipx-file place)"
                ),
            ),
        ),
        (
            "SOPDS_INPX_SKIP_UNCHANGED",
            (
                os.getenv("SOPDS_INPX_SKIP_UNCHANGED", "True").lower()
                in ("1", "true", "yes", "on"),
                _("Skip scanning INPX with unchanged size after previous scan"),
            ),
        ),
        (
            "SOPDS_INPX_TEST_ZIP",
            (
                os.getenv("SOPDS_INPX_TEST_ZIP", "False").lower()
                in ("1", "true", "yes", "on"),
                _(
                    "Test avialability zip files listed in INPX before"
                    " add in collection"
                ),
            ),
        ),
        (
            "SOPDS_INPX_TEST_FILES",
            (
                os.getenv("SOPDS_INPX_TEST_FILES", "False").lower()
                in ("1", "true", "yes", "on"),
                _(
                    "Test avialability book files listed in INPX before"
                    " add in collection"
                ),
            ),
        ),
        (
            "SOPDS_DELETE_LOGICAL",
            (
                os.getenv("SOPDS_DELETE_LOGICAL", "True").lower()
                in ("1", "true", "yes", "on"),
                _("Logical deleting unavialable files"),
            ),
        ),
        (
            "SOPDS_SCAN_SHED_MIN",
            ("0", _("sheduled minutes for sopds_scanner (cron syntax)")),
        ),
        (
            "SOPDS_SCAN_SHED_HOUR",
            ("0,12", _("sheduled hours for sopds_scanner (cron syntax)")),
        ),
        (
            "SOPDS_SCAN_SHED_DAY",
            ("*", _("sheduled day for sopds_scanner (cron syntax)")),
        ),
        (
            "SOPDS_SCAN_SHED_DOW",
            ("*", _("sheduled day of weeks for sopds_scanner (cron syntax)")),
        ),
    ]
)

CONSTANCE_CONFIG_FIELDSETS = {
    "1. General Options": (
        "SOPDS_LANGUAGE",
        "SOPDS_CACHE_TIME",
    ),
    "2. Server Options": (
        "SOPDS_AUTH",
        "SOPDS_ALPHABET_MENU",
        "SOPDS_DOUBLES_HIDE",
        "SOPDS_COVER_SHOW",
        "SOPDS_SPLITITEMS",
        "SOPDS_MAXITEMS",
        "SOPDS_TITLE_AS_FILENAME",
    ),
    "3. Scanner Options": (
        "SOPDS_BOOK_EXTENSIONS",
        "SOPDS_ZIP_ENABLE",
        "SOPDS_ZIP_SKIP_UNCHANGED",
        "SOPDS_ZIP_CODEPAGE",
        "SOPDS_INPX_ENABLE",
        "SOPDS_INPX_SKIP_UNCHANGED",
        "SOPDS_INPX_TEST_ZIP",
        "SOPDS_INPX_TEST_FILES",
        "SOPDS_DELETE_LOGICAL",
    ),
    "4. Scanner Shedule": (
        "SOPDS_SCAN_SHED_MIN",
        "SOPDS_SCAN_SHED_HOUR",
        "SOPDS_SCAN_SHED_DAY",
        "SOPDS_SCAN_SHED_DOW",
        "SOPDS_SCAN_START_DIRECTLY",
    ),
}

SOPDS_ROOT_LIB = os.environ.get("SOPDS_ROOT_LIB", "books/")
SOPDS_NOCOVER_PATH = os.environ.get(
    "SOPDS_NOCOVER_PATH",
    str(STATIC_ROOT / "images/nocover.jpg"),
)
SOPDS_SCAN_WORKERS = int(os.environ.get("SOPDS_SCAN_WORKERS", "0"))
SOPDS_SCAN_DB_BATCH_SIZE = int(os.environ.get("SOPDS_SCAN_DB_BATCH_SIZE", "0"))

SOPDS_SCAN_DB_RETRY_COUNT = int(os.environ.get("SOPDS_SCAN_DB_RETRY_COUNT", "0"))
SOPDS_SCAN_DB_RETRY_DELAY = int(os.environ.get("SOPDS_SCAN_DB_RETRY_DELAY", "0"))

SECURE_REDIRECT_EXEMPT = [r"^health/"]
SECURE_SSL_REDIRECT = os.getenv("DJANGO_SECURE_SSL_REDIRECT", "False").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
SESSION_COOKIE_SECURE = os.getenv("DJANGO_SESSION_COOKIE_SECURE", "False").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
CSRF_COOKIE_SECURE = os.getenv("DJANGO_CSRF_COOKIE_SECURE", "False").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "False"
).lower() in ("1", "true", "yes", "on")
SECURE_HSTS_PRELOAD = os.getenv("DJANGO_SECURE_HSTS_PRELOAD", "False").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
