# Generated by Django 5.2.16 on 2026-07-19 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "opds_catalog",
            "0006_alter_author_id_alter_bauthor_id_alter_bgenre_id_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bookshelf",
            index=models.Index(
                fields=["user", "-readtime"], name="bookshelf_user_readtime_idx"
            ),
        ),
    ]
