# Generated by Django 5.2.16 on 2026-07-22 11:48

from typing import Any

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def validate_unique_relations(apps: Any, schema_editor: Any) -> None:
    relation_specs = (
        ("bauthor", ("book_id", "author_id")),
        ("bgenre", ("book_id", "genre_id")),
        ("bookshelf", ("user_id", "book_id")),
        ("bseries", ("book_id", "ser_id")),
    )

    for model_name, key_fields in relation_specs:
        model = apps.get_model("opds_catalog", model_name)
        duplicate_keys = list(
            model.objects.values(*key_fields)
            .annotate(row_count=Count("id"))
            .filter(row_count__gt=1)
            .order_by(*key_fields)[:10]
        )
        if duplicate_keys:
            raise RuntimeError(
                f"Duplicate {model_name} relation keys must be resolved manually: "
                f"{duplicate_keys}"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("opds_catalog", "0007_bookshelf_bookshelf_user_readtime_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(validate_unique_relations, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="bauthor",
            constraint=models.UniqueConstraint(
                fields=("book", "author"), name="bauthor_book_author_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="bgenre",
            constraint=models.UniqueConstraint(
                fields=("book", "genre"), name="bgenre_book_genre_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookshelf",
            constraint=models.UniqueConstraint(
                fields=("user", "book"), name="bookshelf_user_book_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="bseries",
            constraint=models.UniqueConstraint(
                fields=("book", "ser"), name="bseries_book_series_uniq"
            ),
        ),
    ]
