# Generated by Django 5.2.16 on 2026-07-23

from typing import Any

from django.db import migrations, models
from django.db.models import Count


def validate_unique_entities(apps: Any, schema_editor: Any) -> None:
    entity_specs = (
        ("Book", ("catalog_id", "filename")),
        ("Catalog", ("path",)),
        ("Author", ("full_name",)),
        ("Genre", ("genre",)),
        ("Series", ("ser",)),
    )

    for model_name, key_fields in entity_specs:
        model = apps.get_model("opds_catalog", model_name)
        duplicate_keys = list(
            model.objects.values(*key_fields)
            .annotate(row_count=Count("id"))
            .filter(row_count__gt=1)
            .order_by(*key_fields)[:10]
        )
        if duplicate_keys:
            raise RuntimeError(
                f"Duplicate {model_name} entity keys must be resolved manually: "
                f"{duplicate_keys}"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("opds_catalog", "0008_unique_relation_constraints"),
    ]

    operations = [
        migrations.RunPython(validate_unique_entities, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="book",
            name="path",
        ),
        migrations.RemoveField(
            model_name="book",
            name="cat_type",
        ),
        migrations.AddConstraint(
            model_name="book",
            constraint=models.UniqueConstraint(
                fields=("catalog", "filename"), name="book_catalog_filename_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="catalog",
            constraint=models.UniqueConstraint(
                fields=("path",), name="catalog_path_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="author",
            constraint=models.UniqueConstraint(
                fields=("full_name",), name="author_full_name_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="genre",
            constraint=models.UniqueConstraint(
                fields=("genre",), name="genre_genre_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="series",
            constraint=models.UniqueConstraint(fields=("ser",), name="series_ser_uniq"),
        ),
    ]
