# Generated by Django 5.2.16 on 2026-07-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("opds_catalog", "0009_unique_entity_constraints"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="search_full_name",
        ),
        migrations.RemoveField(
            model_name="book",
            name="search_title",
        ),
        migrations.RemoveField(
            model_name="series",
            name="search_ser",
        ),
    ]
